### ISSUE TITLE
OCAT Not Downloading MOD Versions

### ISSUE THREAD

**Issue by stumay5** [wjz304/OpenCore_NO_ACPI_Build#3]
Hi ING! Not able to download latest MOD OC from the site here. 
There is showing Sync>0.8.2 DEV in the popup do upgrade OpenCore and Kexts
There is showing OpenCore 0.8.2 DEV in the upper left corner of the main window of OCAT
There are three Source links in blue each pointing to a different site as follows:
1 https://dortania.github.io/builds/
2 https://github.com/wjz304/OpenCore_NO_ACPI_Build
3 https://github.com/acidanthera/OcBinaryData/

#1 is the main OpenCore normal version
#2 is the MOD version
#3 is the OcBinaryData 

How to edit these?

In Preferences when setting the sites to the intended->https://github.com/wjz304/OpenCore_NO_ACPI_Build
a popup window opens and complains about this.

So I think the file somewhere needs to be edited? 
Thank you!!

![Screen Shot 2022-11-20 at 4 58 49 PM](https://user-images.githubusercontent.com/64503496/202928843-440cffe3-a576-45dd-81a0-a170f2963ba5.png)
![Screen Shot 2022-11-20 at 4 56 40 PM](https://user-images.githubusercontent.com/64503496/202929058-b2c0c90e-0a14-4191-9c62-72b55db0ff31.png)

**Comment by wjz304** [comment]
非常抱歉， 这在一段时间之前是好使的，但是我忘记了版本，最新的版本确实有问题，我昨天没有去确认最终的文件是否正确。
我想翻阅 OCAT 的源码看一看。给我一些时间。

**Comment by stumay5** [comment]
No problem thank you

**Comment by wjz304** [comment]
经过我的测试 这是 OCAT 的bug，
由于过程比较特殊，我的英语不好，无法表述清楚，所以我将使用中文.

下面的流程将成功同步 Mod版本：
0. 如果OCAT 初始状态 (可以删除  `/Users/<username>/.ocat/*` 恢复)

1. 先切到开发版
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/5615843/202977408-0e5f8a93-583b-4492-8963-4206ccb11424.png">

2.此时先不要 填入 https://github.com/wjz304/OpenCore_NO_ACPI_Build 获取OpenCore，
 先把 url 切到 https://github.com/bugprogrammer/HackinPlugins 获取。将获取到普通版本的 OC。
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/5615843/202979479-759aa2b3-b6f6-44be-8dcf-6e624379a105.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/5615843/202979601-9a943b72-c1a7-45a1-8192-53d22f03500c.png">

3.填入 https://github.com/wjz304/OpenCore_NO_ACPI_Build 获取OpenCore，将正确获取到 Mod OC。
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5615843/202979738-7357f884-84f0-4087-aa7a-8cdea3c6fb0b.png">
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/5615843/202979845-286dcf19-e309-463c-b72c-3972dbf1fc95.png">


第2步，很关键，而且必须先切换到https://github.com/bugprogrammer/HackinPlugins 进行获取，
  默认的 https://github.com/dortania/build-repo 获取也不行，这应该是OCAT的bug，  
如果影响到使用 考虑去 https://github.com/ic005k/OCAuxiliaryTools 提交该 Issue.

**Comment by wjz304** [comment]
> No problem thank you

Please let me know if it works.🤣

**Comment by stumay5** [comment]
HI, it’s not working.

On the hackintosh. 

Siwitchhost doesn’t update still blank.  Had to sudo plus give authorization but no updates with
Addresses.

Not able to gain access to the site.

Thanks

**Comment by wjz304** [comment]
You can try to upgrade your OCAT to the latest version.

In addition, which country or region are you in?
If you are not in China, please do not use the ![image](https://user-images.githubusercontent.com/5615843/203191583-eabc6439-12ad-4c98-b06d-ea10cd2b8ef0.png) tool.

**Comment by wjz304** [comment]
And, the above method, which I tested under Windows, it is also work.

**Comment by stumay5** [comment]
It may be that you might have exclusive access where others outside of yourself cannot access.I live USA. Normally any site is accessible at GitHubMaybe a language issue as well. If it there is not English side full and complete no mixing the slightest bit of another language intermixing will create a stop. The file does get created but is zero bytes.  oc mod 0.8.6 .There is an access issue whether language or otherwise.Thank youSent from my iPhoneOn Nov 21, 2022, at 8:41 PM, Ing ***@***.***> wrote:﻿
And, the above method, which I tested under Windows, it is also work.

**Comment by wjz304** [comment]
@stumay5 

OCAT 更新了，
如果方便，麻烦再次尝试.

BR.
